RecipeKeeper/Controllers/BookController.cs
using Microsoft.AspNet.Identity;
using RecipeKeeper.Models;
using RecipeKeeper.service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecipeKeeper.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        
        // GET: Book
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new BookService(userId);
            var model = service.GetBooks();

            return View(model);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BookCreate model)
        {
            if (!ModelState.IsValid) return View(model);
            
            var service = CreateBookService();

           if (service.CreateBook(model))
            {
                TempData["SaveResult"] = "Your book was saved sucessfully!";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("Fail", "Book could not be created.");
            return View(model);   
        }
        public ActionResult Details(int id)
        {
            var svc = CreateBookService();
            var model = svc.GetBookById(id);

            return View(model);
        }
        public ActionResult Edit(int id)
        {
            var service = CreateBookService();
            var detail = service.GetBookById(id);
            var model = new BookEdit
            {
                BookId = detail.BookId,
                BookName = detail.BookName,
                Author = detail.Author
            };
            return View(model);
           
        }
       [HttpPost]
       [ValidateAntiForgeryToken]

        public ActionResult Edit(int id, BookEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.BookId != id)
            {
                ModelState.AddModelError("", "Id MisMatch");
                return View(model);
            }
            var service = CreateBookService();

            if (service.UpdateBook(model))
            {
                TempData["SaveResult"] = "Your book was updated!";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Your book could not be updated.");
            return View(model);
            
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateBookService();
            var model = svc.GetBookById(id);

            return View(model);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteBook(int id)
        {
            var service = CreateBookService();
            service.DeleteBook(id);
            return RedirectToAction("Index");
        }
        private BookService CreateBookService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new BookService(userId);
            return service;
        }

    }
}

RecipeKeeper/Controllers/IngredientController.cs
using RecipeKeeper.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RecipeKeeper.Data;

using RecipeKeeper.service;

namespace RecipeKeeper.Controllers
{
    [Authorize]
    public class IngredientController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();
        // GET: Ingredient
        public ActionResult Index()
        {
            var service = CreateIngredientService();
            var model = service.GetIngredients();

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IngredientCreate model)
        {
            if (!ModelState.IsValid) return View(model);
         
             var service = CreateIngredientService();
           
           
            if (service.CreateIngredient(model)) 
            {
                TempData["SaveResult"] = "Your ingredient was created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Ingredient could not be created.");
            return View(model);
        } 

        public ActionResult Detail(int id)
        {
            var svc = CreateIngredientService();
            var model = svc.GetIngredientById(id);

            return View(model);
        }

        public ActionResult GetRecipeByIngredient(int id)
        {
            var svc = CreateIngredientService();
            var model = svc.GetRecipesByIngredient(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateIngredientService();
            var detail = service.GetIngredientById(id);
            var model =
                new IngredientEdit
                {
                    IngredientId = detail.IngredientId,
                    IngredientName = detail.IngredientName,
                    IngredientType = detail.IngredientType
                };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IngredientEdit model)
        {
            if(!ModelState.IsValid)return View(model);

            if(model.IngredientId != id)
            {
                ModelState.AddModelError("", "Id MisMatch");
                return View(model);
            }
            var service = CreateIngredientService();

            if (service.UpdateIngredient(model))
            {
                TempData["SaveResult"] = "Your ingredient was updated!";
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Your ingredient could not be updated.");
            return View(model);
        }
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateIngredientService();
            var model = svc.GetIngredientById(id);

            return View(model);
        }
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateIngredientService();
            service.DeleteIngredient(id);
            TempData["SaveResult"] = "Your ingredient was deleted!";
            return RedirectToAction("Index");

        }

        private static IngredientService CreateIngredientService()
        {
            return new IngredientService();
        }

        //GET: Create Ingredient
        public ActionResult Create()
        {
            return View();
        }

       
        
    }
}

RecipeKeeper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - RecipeKeeper</title>
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Ingredients", "Index", "Ingredient")</li>
                        <li>@Html.ActionLink("Recipes", "Index", "Recipe")</li>
                        <li>@Html.ActionLink("Pantry", "Index", "Pantry")</li>
                        <li>@Html.ActionLink("Books", "Index", "Book")</li>
                    }

                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - RecipeKeeper</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>